[BASIC]
IS_LOW_BEAM_AVAILABLE=1
IS_HIGH_BEAM_AVAILABLE=1

[MODEL_REPLACEMENT_...]
FILE=toyota_gr_supra_racing.kn5
INSERT=lumi.kn5
INSERT_AFTER=COCKPIT_HR

[MODEL_REPLACEMENT_...]
FILE=toyota_gr_supra_racing_lod_b.kn5
INSERT=lumi.kn5
INSERT_AFTER=COCKPIT_LR

[MODEL_REPLACEMENT_...]
FILE=toyota_gr_supra_racing_lod_c.kn5
INSERT=lumi.kn5
INSERT_AFTER=COCKPIT_LR


[MODEL_REPLACEMENT_...]
FILE=toyota_gr_supra_racing_lod_d.kn5
INSERT=lumi.kn5
INSERT_AFTER=COCKPIT_LR


[DATA]
DISABLE_DIGITALPANELSINI = 1

[SHADER_REPLACEMENT_...]
MATERIALS = LUMIRANK
SHADER = ksPerPixelMultiMap_emissive
FILL_MISSING_TEXTURES = 1
PROP_... = emSkipDiffuseMap, 1
PROP_... = ksEmissive, 400, 400, 400

[LED_PANEL_...]
MESHES = lumirank_3     ; target mesh
TEXTURE_SLOT = txEmissive       ; target texture slot
RESOLUTION = 1024, 512          ; resolution of newly generated texture
MASKS_PACK = lumirank_font.zip  ; name of a pack with LED masks
DIGIT_0 = 13, 5, 310, 256      ; X, Y, width and height of a first digit
DIGIT_1 = 358, 5, 310, 256     ; X, Y, width and height of a second digit
DIGIT_2 = 707, 5, 310, 256     ; X, Y, width and height of a third digit
                                ; you can set as many digits as you need

BASE_COLOR = '#1941c2', 0.5    ; base color (when it’s not flashing)
FLASHING_COLOR = '#1941c2', 0.05  ; color for flashing
FLASHING_APPLY_MASK = 1        ; should mask be applied to flashing

N24_FLASHING_PERIOD = 3.5        ; N24 flashing: period in seconds
N24_FLASHING_TIME = 1.2          ; for how long it would flash in seconds
N24_FLASHING_FREQUENCY = 6       ; flashing frequency in Hz
N24_FLASHING_ACTIVE_SHARE = 0.7  ; how much time during flashing it spends in active stage

BLANCPAIN_FLASHING_PERIOD = 0       ; Blancpain flashing: period in seconds
BLANCPAIN_FLASHING_DURATION = 0   ; for how long it shuts off, in seconds
BLANCPAIN_FLASHING_RACE_CLASS = PRO  ; race class (it would flash only for a leader in class)

ROLE_0 = TEXT  ; first role
ROLE_0_TEXT = GT2     ; first role text
ROLE_1 = POSITION     ; second role
ROLE_2 = TEXT     ; second role
ROLE_2_TEXT = SPR     ; you can set as many roles as you need

ROLE_DURATION = 3     ; how much time in seconds each role lasts
